### ISSUE TITLE
[Feat] 화면 연결 및 메뉴 시트

### ISSUE THREAD

**Issue by JMM00** [Gwamegis/Moya-Android#51]
### Todo
- [x] 탭 - 음악 재생 화면 연결
- [ ] 팀 선택 시트 연결
- [ ] 메인 화면 시트 연결
- [ ] 좋아요 기능 연결
